[package]
name = "veles_night"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = { version = "*", features=["wayland"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
